name: Major Monitor

on:
  schedule:
    - cron: '32 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script
        run: python main.py

      - name: Commit database
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "github-actions"
          git add sent_ads.json
          git commit -m "Update sent ads database" || echo "No changes"
          git push
